version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    container_name: airflow_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: airflow_webserver
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - "/C/Users/tredo/OneDrive/Desktop/Learning/DataScience/Data Projects/EIA_Analysis/dags:/opt/airflow/dags"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - "/C/Users/tredo/OneDrive/Desktop/Learning/DataScience/Data Projects/EIA_Analysis/dags:/opt/airflow/dags"
    command: scheduler

volumes:
  postgres_data:
